[package]
name = "solver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meval = "0.2.0"
gnuplot = "0.0.37"

[[bin]]
name = "solver"

